NewsPaper_project/NewsPaper/urls.py
"""
URL configuration for NewsPaper project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views:
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views:
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf:
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from accounts.views import become_author
from news.views import (ArticleCreateView, ArticleUpdateView, ArticleDeleteView
)

urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('articles/create/', ArticleCreateView.as_view(), name='article-create'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article-update'),
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('become-author/', become_author, name='become_author'),
]

NewsPaper_project/news/urls.py
from django.urls import path, include
from .views import (
    NewsListView, NewsSearchView, NewsCreateView,
    NewsUpdateView, NewsDeleteView, CurrentPost, category_posts
)


urlpatterns = [
    path('', NewsListView.as_view(), name='news-list'),
    path('search/', NewsSearchView.as_view(), name='news-search'),
    path('create/', NewsCreateView.as_view(), name='news-create'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='news-update'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news-delete'),
    path('<int:pk>/', CurrentPost.as_view(), name='news-current'),
    path('category/<int:category_id>/', category_posts, name='category_posts'),
]

NewsPaper_project/news/models.py
from django.db import models
import accounts.models as account_models

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(
        account_models.User,
        blank=True,
        related_name='subscribed_categories'
    )

    def __str__(self):
        return self.name

class Post(models.Model):
    article = 'AR'
    news = 'NE'
    POSITIONS = [
        (article, 'Cтатья'),
        (news, 'Новость')
    ]

    author = models.ForeignKey(account_models.Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=POSITIONS, default=article)
    created = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating = models.FloatField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.content[:124] + '...'

    def __str__(self):
        return f'{self.title} – {self.author.user.username}: {self.content[:124]}...'

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post.title} – {self.category.name}'

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(account_models.User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.user.username} – {self.post.title}'

NewsPaper_project/news/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.shortcuts import render

from .models import Post, Category
from .filters import NewsFilter
from accounts.models import Author

from django.shortcuts import get_object_or_404, redirect, render


def category_posts(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    posts = Post.objects.filter(category=category).order_by('-created')
    return render(request, 'news/category_posts.html', {
        'category': category,
        'posts': posts,
    })

class NewsListView(LoginRequiredMixin, ListView):
    model = Post
    ordering = '-created'
    template_name = 'news/news_list.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['time_now'] = timezone.now()
        ctx['selected_category'] = None
        return ctx

class NewsSearchView(LoginRequiredMixin, ListView):
    model = Post
    ordering = '-created'
    template_name = 'news/news_list.html'
    context_object_name = 'news'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        sub_id = request.GET.get('subscribe')
        if sub_id and request.user.is_authenticated:
            cat = get_object_or_404(Category, pk=sub_id)
            if request.user not in cat.subscribers.all():
                cat.subscribers.add(request.user)

        unsub_id = request.GET.get('unsubscribe')
        if unsub_id and request.user.is_authenticated:
            cat = get_object_or_404(Category, pk=unsub_id)
            if request.user in cat.subscribers.all():
                cat.subscribers.remove(request.user)

        if sub_id or unsub_id:
            params = request.GET.copy()
            params.pop('subscribe', None)
            params.pop('unsubscribe', None)
            return redirect(f"{request.path}?{params.urlencode()}")

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset=qs)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['filterset'] = self.filterset

        cat_id = self.request.GET.get('category')
        if cat_id:
            ctx['selected_category'] = get_object_or_404(Category, pk=cat_id)
        else:
            ctx['selected_category'] = None

        return ctx

class CurrentPost(DetailView):
    model = Post
    template_name = 'news/news_detail.html'
    context_object_name = 'post'

class NewsCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    fields = ['category', 'title', 'content']
    template_name = 'news/news_form.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.add_post'

    def form_valid(self, form):
        author = Author.objects.get(user=self.request.user)
        now = timezone.now()
        start_day = now.replace(hour=0, minute=0, second=0, microsecond=0)
        today_count = Post.objects.filter(
            author=author,
            created__gte=start_day
        ).count()

        if today_count >= 3:
            form.add_error(None, 'Вы уже создали три новости сегодня — лимит исчерпан.')
            return self.form_invalid(form)
        form.instance.type = 'NE'
        form.instance.author = Author.objects.get(user=self.request.user)
        return super().form_valid(form)

class NewsUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    fields = ['category', 'title', 'content']
    template_name = 'news/news_form.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.change_post'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.type != 'NE':
            return HttpResponseForbidden("Изменение не разрешено для данного типа объекта.")
        return super().dispatch(request, *args, **kwargs)

class NewsDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.delete_post'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.type != 'NE':
            return HttpResponseForbidden("Удаление не разрешено для данного типа объекта.")
        return super().dispatch(request, *args, **kwargs)

class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    fields = ['category', 'title', 'content']
    template_name = 'news/article_form.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.add_post'

    def form_valid(self, form):
        author = Author.objects.get(user=self.request.user)
        now = timezone.now()
        start_day = now.replace(hour=0, minute=0, second=0, microsecond=0)
        today_count = Post.objects.filter(
            author=author,
            created__gte=start_day
        ).count()

        if today_count >= 3:
            form.add_error(None, 'Вы уже создали три новости сегодня — лимит исчерпан.')
            return self.form_invalid(form)
        form.instance.type = 'AR'
        form.instance.author = Author.objects.get(user=self.request.user)
        return super().form_valid(form)

class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    fields = ['category', 'title', 'content']
    template_name = 'news/article_form.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.change_post'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.type != 'AR':
            return HttpResponseForbidden("Изменение не разрешено для данного типа объекта.")
        return super().dispatch(request, *args, **kwargs)

class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = 'news/article_confirm_delete.html'
    success_url = reverse_lazy('news-list')
    permission_required = 'news.delete_post'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.type != 'AR':
            return HttpResponseForbidden("Удаление не разрешено для данного типа объекта.")
        return super().dispatch(request, *args, **kwargs)

NewsPaper_project/templates/news/article_confirm_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
Удаление новости – {{ object.title }}
{% endblock title %}

{% block content %}
<h1><b><span style="color: #272a2d;">Удаление статьи</span></b></h1>
<hr>
<p style="font-size: 1.1rem;">Вы уверены, что хотите удалить новость:</p>
<p style="font-style: italic; color: #8199ff;">"{{ object.title }}"</p>

<form method="post" style="margin-top: 2rem;">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-secondary ml-2">Подтвердить удаление</button>
    <a href="{% url 'news-current' object.pk %}" class="btn btn-success ml-2">Отмена</a>
</form>
{% endblock content %}

NewsPaper_project/templates/news/article_form.html
{% extends 'news/news_list.html' %}

{% block title %}
    Создание/Редактирование статьи
{% endblock title %}

{% block content %}
<h1><b><span style="color: #272a2d;">Создание / Редактирование статьи</span></b></h1>
<hr>
<form method="post" style="margin-top: 2rem;">
    {% csrf_token %}
    <div style="max-width: 600px; margin: 0 auto;">
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-3">💾 Сохранить</button>
    </div>
    </form>
<style>
    input, textarea, select {
        border-radius: 0.5rem;
        padding: 8px;
        border: 1px solid #e0e5ff;
    }
</style>
{% endblock content %}

NewsPaper_project/templates/news/category_posts.html
{# templates/news/category_posts.html #}
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Категория: {{ category.name|censor }}
{% endblock title %}

{% block content %}
  <h1><b><span style="color: #272a2d;">Новости раздела «{{ category.name|censor }}»</span></b></h1>



  <hr>

  {% for post in posts %}
    <h2 style="margin-top: 2rem;">
      <b><span style="color: #272a2d;">
        <a href="{% url 'news-current' post.pk %}">{{ post.title|censor }}</a>
      </span></b>
    </h2>
    <i><span style="color: #8199ff;">
      {{ post.author.user.username }} – {{ post.created|date:"d.m.Y" }}
    </span></i>
    <br>
    <p>{{ post.content|slice:":124" }}…</p>
    <hr>
  {% empty %}
    <p>В этой категории пока нет новостей.</p>
  {% endfor %}
{% endblock content %}

NewsPaper_project/templates/news/news_confirm_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
Удаление новости – {{ object.title }}
{% endblock title %}

{% block content %}
<h1><b><span style="color: #272a2d;">Удаление новости</span></b></h1>
<hr>
<p style="font-size: 1.1rem;">Вы уверены, что хотите удалить новость:</p>
<p style="font-style: italic; color: #8199ff;">"{{ object.title }}"</p>

<form method="post" style="margin-top: 2rem;">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-secondary ml-2">Подтвердить удаление</button>
    <a href="{% url 'news-current' object.pk %}" class="btn btn-success ml-2">Отмена</a>
</form>
{% endblock content %}

NewsPaper_project/templates/news/news_detail.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
{{ post.get_type_display }} - {{ post.title|censor }} ({{ post.author.user.username }})
{% endblock title %}

{% block content %}
<h1><b><span style="color: #272a2d;">{{ post.title|censor }}</span></b></h1>
<i><span style="color: #8199ff;"><b>{{ post.author.user.username }}</b> – {{ post.created|date:"d.m.Y" }}</span></i>
<hr>

<br>{{ post.content|censor }}

{% if request.user.username == post.author.user.username %}
    <div style="margin-top: 2rem;">
        {% if post.type == 'NE' %}
            <a href="{% url 'news-update' post.pk %}" class="btn btn-outline-primary">Редактировать</a>
            <a href="{% url 'news-delete' post.pk %}" class="btn btn-outline-danger">Удалить</a>
        {% elif post.type == 'AR' %}
            <a href="{% url 'article-update' post.pk %}" class="btn btn-outline-primary">Редактировать</a>
            <a href="{% url 'article-delete' post.pk %}" class="btn btn-outline-danger">Удалить</a>
        {% endif %}
    </div>
{% endif %}
{% endblock content %}

NewsPaper_project/templates/news/news_form.html
{% extends 'flatpages/default.html' %}

{% block title %}
Создание/Редактирование новости
{% endblock title %}

{% block content %}
<h1><b><span style="color: #272a2d;">Создание / Редактирование новости</span></b></h1>
<hr>

<form method="post" style="margin-top: 2rem;">
    {% csrf_token %}
    <div style="max-width: 600px; margin: 0 auto;">
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-3">💾 Сохранить</button>
    </div>
</form>
<style>
    input, textarea, select {
        border-radius: 0.5rem;
        padding: 8px;
        border: 1px solid #e0e5ff;
    }
</style>
{% endblock content %}

NewsPaper_project/templates/news/news_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load static %}

{% block title %}
Все новости
{% endblock title %}

{% block content %}
<h1><b>Все новости <sup style="font-size: 0.6em; color: #8199ff;">{% news_counter %}</sup></b></h1>
<h5><i><span style="color: #8199ff; font-size: 0.8em;">{{ time_now }}</span></i></h5>


{% if filterset %}
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" class="btn-primary" value="Поиск" />
    </form>

    <style>
        input, textarea, select {
            border-radius: 0.5rem;
            padding: 2px;
            border: 1px solid #e0e5ff;
        }
        input[type="submit"][value="Поиск"] {
            background-color: #3668df;
            color: white;
            font-weight: bold;
            padding: 0.2rem 0.7rem;
            border: none;
            border-radius: 0.5rem;
            cursor: pointer;
            transition: background 0.3s;
        }
        input[type="submit"][value="Поиск"]:hover {
            background-color: #2f5ac4;
        }
    </style>
{% endif %}


{% if request.user|has_group:"authors" %}
<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
    <!-- Левая часть -->
    <div style="display: flex; gap: 0.5rem;">
        <a href="/articles/create/" class="page-btn" title="Создать статью">➕ Статья</a>
        <a href="/news/create/" class="page-btn" title="Создать новость">➕ Новость</a>
        {% if selected_category %}
            {% if request.user in selected_category.subscribers.all %}
                <a
      href="?{% url_replace unsubscribe=selected_category.id %}"
      class="page-btn current"
      style="opacity: 0.8;"
      title="Отписаться"
    >Подписан</a>
            {% else %}
                <a href="?{% url_replace subscribe=selected_category.id %}" class="page-btn">✅ Подписаться</a>
            {% endif %}
        {% endif %}
    </div>


    <!-- Правая часть -->
    {% if filterset %}
        <a href="/news/" class="page-btn">
            <img src="{% static 'img/filter_close.svg' %}" alt="Фильтры" style="width: 20px; height: 20px;">
        </a>
    {% else %}
        <a href="search/" class="page-btn">
            <img src="{% static 'img/filter_open.svg' %}" alt="Фильтры" style="width: 20px; height: 20px;">
        </a>
    {% endif %}
</div>
{% else %}
<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
    <!-- Левая часть -->
    <div style="display: flex; gap: 0.5rem;">
        {% if selected_category %}
            {% if request.user in selected_category.subscribers.all %}
                <a
      href="?{% url_replace unsubscribe=selected_category.id %}"
      class="page-btn current"
      style="opacity: 0.8;"
      title="Отписаться"
    >Подписан</a>
            {% else %}
                <a href="?{% url_replace subscribe=selected_category.id %}" class="page-btn">✅ Подписаться</a>
            {% endif %}
        {% endif %}
    </div>


    <!-- Правая часть -->
    {% if filterset %}
        <a href="/news/" class="page-btn">
            <img src="{% static 'img/filter_close.svg' %}" alt="Фильтры" style="width: 20px; height: 20px;">
        </a>
    {% else %}
        <a href="search/" class="page-btn">
            <img src="{% static 'img/filter_open.svg' %}" alt="Фильтры" style="width: 20px; height: 20px;">
        </a>
    {% endif %}
</div>
{% endif %}

{% if news %}
    <table style="width: 100%; margin-top: 1rem;">
        <tr>
            <td class="col-title" style="border-top-left-radius: 0.5rem; border-bottom-left-radius: 0.5rem;"><b>Заголовок</b></td>
            <td class="col-title"><b>Дата</b></td>
            <td class="col-title" style="border-top-right-radius: 0.5rem; border-bottom-right-radius: 0.5rem;"><b>Содержание</b></td>
        </tr>
        {% for item in news %}
        <tr class="clickable-row" onclick="window.location.href='{% url 'news-current' item.pk %}';" style="cursor: pointer;">
            <td class="col-row">{{ item.title|censor }}</td>
            <td class="col-row">{{ item.created|date:"d.m.Y" }}</td>
            <td class="col-content">{{ item.content|censor|truncatewords:20 }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>Нет новостей!</h2>
{% endif %}

{% if paginator.num_pages > 1 %}
<div style="margin-top: 2rem; display: flex; justify-content: center; gap: 0.5rem; flex-wrap: wrap;">

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}" class="page-btn">1</a>
        <a href="?{% url_replace page=page_obj.previous_page_number %}" class="page-btn">◀</a>
    {% endif %}

    <span class="page-btn current">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}" class="page-btn">▶</a>
        <a href="?{% url_replace page=paginator.num_pages %}" class="page-btn">{{ paginator.num_pages }}</a>
    {% endif %}

</div>
{% endif %}

<style>
    .page-btn {
        display: inline-block;
        padding: 6px 12px;
        font-size: 14px;
        color: #000000;
        border: 1px solid #e0e5ff;
        border-radius: 0.4rem;
        text-decoration: none;
        background-color: #f7f9ff;
        transition: all 0.2s;
    }

    .page-btn:hover {
        background-color: #dce5ff;
        color: #274bbf;
    }

    .page-btn.current {
        background-color: #3668df;
        color: white;
        font-weight: bold;
        border: 1px solid #3668df;
        cursor: default;
    }
</style>
{% endblock content %}